package com.example.drools;

import com.example.drools.dto.User;
import com.example.drools.dto.RuleResult

global java.util.List results;

dialect "mvel"

// ================= AGE =================

rule "Age Approved"
activation-group "age-group"
when
    $u : User(age > 18 && age <= 50)
then
    results.add(new RuleResult(
        "AGE",
        "APPROVED",
        $u.getAge(),
        "18<Age<=50"
    ));
end

rule "Age Rejected"
activation-group "age-group"
when
    $u : User(age <= 18 || age > 50)
then
    results.add(new RuleResult(
        "AGE",
        "REJECTED",
        $u.getAge(),
        "Age<=18 OR Age>50"
    ));
end


// ================= SALARY =================

rule "Salary Approved"
activation-group "salary-group"
when
    $u : User(salary > 100000)
then
    results.add(new RuleResult(
        "SALARY",
        "APPROVED",
        $u.getSalary(),
        "Salary>100000"
    ));
end

rule "Salary Rejected"
activation-group "salary-group"
when
    $u : User(salary <= 100000)
then
    results.add(new RuleResult(
        "SALARY",
        "REJECTED",
        $u.getSalary(),
        "Salary<=100000"
    ));
end


// ================= DEBT =================

rule "Debt Approved"
activation-group "debt-group"
when
    $u : User(debt < 20000)
then
    results.add(new RuleResult(
        "DEBT",
        "APPROVED",
        $u.getDebt(),
        "Debt<20000"
    ));
end

rule "Debt Rejected"
activation-group "debt-group"
when
    $u : User(debt >= 20000)
then
    results.add(new RuleResult(
        "DEBT",
        "REJECTED",
        $u.getDebt(),
        "Debt>=20000"
    ));
end